### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MacAddressTableRecorder#1]
### Collaboration

- [x] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [x] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [x] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- #02
- #03
- #04
- #05
- [x] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [x] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [x] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [x] Read [Management of Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/ConflictManagement/ConflictManagement.md)
- [x] Read [Avoiding Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/AvoidingConflicts/AvoidingConflicts.md)
- #06

#### ServiceList

- [x] Read [Structure of Services](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfServices/StructureOfServices.md)
- [x] Read [Structure of ServiceNames](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfServiceNames/StructureOfServiceNames.md)
- [x] Read [Structure of Release Numbers](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfReleaseNumbers/StructureOfReleaseNumbers.md)
- [x] Read [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md) in general and for details about Servers and Clients
- [x] Read [Concept of ServiceList](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/ConceptOfServiceList/ConceptOfServiceList.md)
- [x] #010

#### ProfileList

- [x] Read [Concept of Profiles](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfiles/ConceptOfProfiles.md)
- [x] [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md) in general and for details about Profiles
- [x] Read [Concepts of ProfileList and ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfileList/ConceptOfProfileList.md)
- [x] #011
- [x] #012

#### ForwardingList

- [x] Read [Concepts of Internal Forwarding](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptsOfInternalForwarding/ConceptsOfInternalForwarding.md)
- [x] Read [Structure of Internal Forwardings](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/StructureOfInternalForwarding/StructureOfInternalForwarding.md)
- [x] Read [Types of Internal Forwardings](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/TypesOfInternalForwardings/TypesOfInternalForwardings.md)
- [x] Read [Substructure of Management of Internal Forwarding](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/SubstructureOfManagementOfInternalForwardings/SubstructureOfManagementOfInternalForwardings.md)
- [x] Read [Structure of Internal Forwarding Names](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfInternalForwardingNames/StructureOfInternalForwardingNames.md)
- [x] Read [Concepts of the _ForwardingList_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptsOfForwardingList/ConceptsOfForwardingList.md)
- [x] Read [Structure of the _ForwardingList_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfForwardingList/StructureOfForwardingList.md)
- [x] Read [Structure of a Description of a _Forwarding_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfForwardingDescription/StructureOfForwardingDescription.md)
- [x] #020

#### CONFIGfile

- [x] Read [Concept of the CONFIGfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptOfConfigFile/ConceptOfConfigFile.md)
- [x] Read [Concept of the DATAfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptOfDataFile/ConceptOfDataFile.md)
- [x] Read [Structure of the CONFIGfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/StructureOfConfigFile/StructureOfConfigFile.md)
- [x] Read [ONF Core Model Overview](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/Overview/Overview.md)
- [x] Read [ControlConstruct](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/ControlConstruct/ControlConstruct.md)
- [x] Read [ProfileCollection and Profile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/Profile/Profile.md)
- [x] Read [LogicalTerminationPoint and LayerProtocol](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/LogicalTerminationPoint/LogicalTerminationPoint.md)
- [x] Read [ForwardingDomain, ForwardingConstruct and ForwardingConstructPort](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/ForwardingConstruct/ForwardingConstruct.md)
- [x] #021

#### OAS

- [x] Read [Concept of Microservice](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/Microservice/Microservice.md)
- (['Microservices' at Wikipedia site](https://de.wikipedia.org/wiki/Microservices) could also be read for a bit more complete picture)
- [x] Read [Introduction to HTTP Requests](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/Http/Http.md)
- [x] Read about the [API-First Approach](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/ApiFirst/ApiFirst.md)
- [x] Read about the [OpenAPI Specification](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/OpenApiSpecification/OpenApiSpecification.md) definitions
- [x] Read the [OpenAPI Guide from Basic Structure to Using $ref](https://swagger.io/docs/specification/basic-structure/)
- (In case of any doubts during applying OpenAPI Specification, looking into its [definition](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#oasDocument) might help, but it is not recommended to read the entire document.)
- [ ] Open an existing OAS (e.g. [RegistryOffice](https://github.com/openBackhaul/RegistryOffice/blob/develop/spec/RegistryOffice.yaml)) and study it line by line while reading [Structure of the OAS](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfOas/StructureOfOas.md)
- [x] #022
