### ISSUE TITLE
RoadMap for Implementing MATR

### ISSUE THREAD

**Issue by schiavi-siae** [openBackhaul/MacAddressTableRecorder#63]
# Roadmap

## Clean Coding

* Read [Introduction to CleanCode](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/ConceptOfCleanCoding/ConceptOfCleanCoding.md)
* Read [coding guidelines](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/PreparingSpecifying/ConceptOfCodingGuidelines/ConceptOfCodingGuidelines.md)

- [x] Activity#1 [Configure Automatic Code Style and Formatting](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/CleanCoding/Activity2ConfigureAutomaticCodeStyleAndFormatting.md)

## Repository Basic Setup

* Read [Directory for server-side implementation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfDirectoryForServer/ConceptOfDirectoryForServer.md)
* Read [About .gitignore file](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfGitIgnoreFile/ConceptOfGitIgnoreFile.md)

- [x] Activity#1 [Create Directory for server-side implementation](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/RepositoryBasicSetup/Activity2CreateDirectoryForServerSide.md)
- [x] Activity#2 [Create .gitignore file](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/RepositoryBasicSetup/Activity2CreateGitignoreFile.md)

## Server Stub Generation 

- [x] #69

## Dependencies and Initial Configuration

* Read [Integrating Configuration file](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfIntegratingConfigFile/ConceptOfIntegratingConfigFile.md)
* Read [Application pattern package](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfApplicationPatternPackage/ConceptOfApplicationPatternPackage.md)
* Read [Authorization](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfAuthenticationAuthorization/ConceptOfAuthenticationAuthorization.md)
* Read [Directing Logs and Traces](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfLogDirection/ConceptOfLogDirection.md)

- [x] Activity#1 [Integrate Configuration file](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/DependenciesAndInitialConfiguration/Activity2IntegrateConfigurationFile.md)
- [x] Activity#2 [Integrate Application pattern package](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/DependenciesAndInitialConfiguration/Activity2IntegrateApplicationPatternPackage.md)
- [x] Activity#3 [Integrate Logging application](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/DependenciesAndInitialConfiguration/Activity2IntegrateLoggingApplication.md)
- [x] Activity#4 [Integrate Authorization](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/DependenciesAndInitialConfiguration/Activity2IntegrateAuthorization.md)

## Basic Services  

* Read [Basic Service packages](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfBasicServices/ConceptOfBasicServices.md)

- [x] #79

## OAM Services

* Read [OAM Services](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfOAMServices/ConceptOfOAMServices.md)

- [x] #85

## Individual Services 

* Read [Individual Services](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfIndividualServices/ConceptOfIndividualServices.md)
* Read [software upgradation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfSoftwareUpgradation/ConceptOfSoftwareUpgradation.md)
* Read [Generic representation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfGenericRepresentation/ConceptOfGenericRepresentation.md)

- [x] Activity#1 #81
- [x] Activity#2 [Implement Services](https://github.com/openBackhaul/ApplicationImplementerTrainingTemplate/blob/develop/doc/RoadMap/IndividualServices/Activity2ImplementIndividualServices.md)
