### ISSUE TITLE
RoadMap for Implementing MATR

### ISSUE THREAD

**Issue by schiavi-siae** [openBackhaul/MacAddressTableRecorder#64]
# Roadmap

## Repository Basic Setup

* Read [Directory for server-side implementation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfDirectoryForServer/ConceptOfDirectoryForServer.md)
* Read [About .gitignore file](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfGitIgnoreFile/ConceptOfGitIgnoreFile.md)

- [ ] Activity#1 [Create Directory for server-side implementation](./RepositoryBasicSetup/Activity2CreateDirectoryForServerSide.md)
- [ ] Activity#2 [Create .gitignore file](./RepositoryBasicSetup/Activity2CreateGitignoreFile.md)

## Understanding the Requirement

* Read [Understanding the CONFIG file](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfUnderstandingTheConfigFile/ConceptOfUnderstandingTheConfigFile.md)
* Read [Understanding the OAS](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfUnderstandingTheOAS/ConceptOfUnderstandingTheOAS.md)

- [ ] Activity#1 [Get a high-level overview](./UnderstandingTheRequirement/Activity2GetAHighLevelOverview.md)
- [ ] Activity#2 [Resolve OAS issue related to basic service](./UnderstandingTheRequirement/Activity2ResolveOASIssueRelatesToBasicService.md)
- [ ] Activity#3 [Resolve OAS issue related to missing header](./UnderstandingTheRequirement/Activity2ResolveOASIssueRelatesToMissingHeader.md)
- [ ] Activity#4 [Resolve OAS issue related to uuid](./UnderstandingTheRequirement/Activity2ResolveOASIssueRelatesToUuid.md)
- [ ] Activity#5 [Resolve CONFIGFile issue related to Individual service](./UnderstandingTheRequirement/Activity2ResolveCONFIGFileIssueRelatesToIndividualService.md)
- [ ] Activity#6 [Resolve CONFIGFile issue related to Forwarding Construct](./UnderstandingTheRequirement/Activity2ResolveCONFIGFileIssueRelatesToForwardingConstruct.md)
- [ ] Activity#7 [Resolve CONFIGFile issue related to uuid](./UnderstandingTheRequirement/Activity2ResolveCONFIGFileIssueRelatesToUuid.md)
- [ ] Activity#8 [Resolve CONFIGFile issue related to operation-key](./UnderstandingTheRequirement/Activity2ResolveCONFIGFileIssueRelatesToOperationKey.md)

## Server Stub Generation 

- [ ] Activity#1 [Generate server side stub](./ServerStubGeneration/Activity2GenerateServerSideStub.md)
- [ ] Activity#2 [Validate the server side code](./ServerStubGeneration/Activity2ValidateServerSideCode.md)
- [ ] Activity#3 [Upload the generated server stub](./ServerStubGeneration/Activity2UploadTheStub.md)

## Dependencies and Initial Configuration

* Read [Integrating Configuration file](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfIntegratingConfigFile/ConceptOfIntegratingConfigFile.md)
* Read [Application pattern package](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfApplicationPatternPackage/ConceptOfApplicationPatternPackage.md)
* Read [Authorization](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfAuthenticationAuthorization/ConceptOfAuthenticationAuthorization.md)
* Read [Directing Logs and Traces](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfLogDirection/ConceptOfLogDirection.md)

- [ ] Activity#1 [Integrate Configuration file](./DependenciesAndInitialConfiguration/Activity2IntegrateConfigurationFile.md)
- [ ] Activity#2 [Integrate Application pattern package](./DependenciesAndInitialConfiguration/Activity2IntegrateApplicationPatternPackage.md)
- [ ] Activity#3 [Integrate Logging application](./DependenciesAndInitialConfiguration/Activity2IntegrateLoggingApplication.md)
- [ ] Activity#4 [Integrate Authorization](./DependenciesAndInitialConfiguration/Activity2IntegrateAuthorization.md)

## Basic Services  

* Read [Basic Service packages](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfBasicServices/ConceptOfBasicServices.md)

- [ ] Activity#1 [Integrate Basic Service](./BasicServices/Activity2IntegrateBasicServices.md)

## OAM Services

* Read [OAM Services](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfOAMServices/ConceptOfOAMServices.md)

- [ ] Activity#1 [Implement OAM Services](./OAMServices/Activity2ImplementOAMServices.md)

## Individual Services 

* Read [Individual Services](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfIndividualServices/ConceptOfIndividualServices.md)
* Read [software upgradation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfSoftwareUpgradation/ConceptOfSoftwareUpgradation.md)
* Read [Generic representation](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ImplementingApplications/ConceptOfGenericRepresentation/ConceptOfGenericRepresentation.md)

- [ ] Activity#1 [Implement Individual Services](./IndividualServices/Activity2ImplementIndividualServices.md)

**Comment by schiavi-siae** [comment]
Duplicated issue
